spring:
  application:
    name: SpringbootMVC

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  security:
    user:
      name: admin
      password: admin123s

server:
  port: 7070